name: 'Example'
on:
  pull_request:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:


jobs:
  discovery: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      # Configure Nix
      - uses: nixbuild/nix-quick-install-action@v22
        with:
          nix_conf: |
            experimental-features = nix-command flakes
            accept-flake-config = true
            trusted-users = runner
            access-tokens = github.com=${{ github.token }}

      # Execute Discovery. It will schedule builds on `worker` job below
      - uses: DevPalace/phoenix-ci/discovery@v1.1
        id: discovery
        with:
          # Attribute paths to search for targets
          attrPaths: ci.x86_64-linux.default, packages.x86_64-linux

          # Disable caching since discovery does not do much most of the time
          nixStoreCachingEnabled: false
          nixEvalCacheCachingEnabled: false
    outputs:
      hits: ${{ steps.discovery.outputs.hits }}


  worker:
    name: "${{ matrix.target.attrPath }}"
    needs: [discovery]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJSON(needs.discovery.outputs.hits) }}
    steps:
      # Configure Nix
      - uses: nixbuild/nix-quick-install-action@v22
        with:
          nix_conf: |
            experimental-features = nix-command flakes
            accept-flake-config = true
            trusted-users = runner
            access-tokens = github.com=${{ github.token }}

      # Executes builds per each found target in discovery
      - uses: DevPalace/phoenix-ci/worker@v1.1
        id: worker
        with:
          target: ${{ toJSON(matrix.target) }}

